name: CI con Docker

on: [push]

jobs:
  construir-y-probar-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Construir la imagen de Docker
        run: docker build -t mi-app-python .

      - name: Ejecutar el contenedor Docker
        run: docker run --rm mi-app-python