name: Docker Programado DEV a las 13:50 Chile

on:
  schedule:
    # 13:50 de Chile en horario actual (UTC-3) son las 16:50 UTC
    - cron: '50 16 * * *'
  workflow_dispatch: # Mantiene el botón para probarlo manualmente cuando quieras

jobs:
  ejecutar-docker-programado:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Construir la imagen de Docker
        run: docker build -t mi-app-python-programado .

      - name: Ejecutar el contenedor Docker
        run: docker run --rm mi-app-python-programado